### ISSUE TITLE
Old URP [Spacewarp] Package

### ISSUE THREAD

**Issue by davoodkharmanzar** [Oculus-VR/Unity-Graphics#36]
hey,

does a plan to update **Spacewarp-URP** packages for **2023.2.x**? [URP 16.x]

thanks.

**Comment by Theundeadwarrior** [comment]
Hey there. I don't think there's a plan to support 2023.2 since it's not an LTS release. There is a branch for Unity 6.0 here https://github.com/Oculus-VR/Unity-Graphics/tree/6000.0/oculus-app-spacewarp. I'm not sure what the delta is between 2023.2 and 6.0 but should be easy-ish to port in case you really need it for 2023.2.
